export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_LANDING = 'FETCH_LANDING';
export const GET_TEAMDATA = 'GET_TEAMDATA';

export const POST_USERDATA = 'POST_USERDATA';
export const GET_USERDATA = 'GET_USERDATA';
export const LOGOUT_USERDATA = 'LOGOUT_USERDATA';
export const GET_USERDATA_REDUX = 'GET_USERDATA_REDUX';
